version: "{build}"

platform:
  - x86
  - x64
  - Any CPU

configuration:
  - Debug
  - Release

install:

before_build:
  - ps: Get-ChildItem -force

build:
  project: src\AprioriAll.sln

test_script:
  - vstest.console /logger:Appveyor /TestCaseFilter:"FullyQualifiedName~AprioriTest|FullyQualifiedName~AprioriAllTest" bin\AprioriAllLibTest.dll
